export * from "./qualificationDialog";
export * from "./patientDetailsDialog";
export * from './consultationModalDialog';
export * from './appointmentDetail';
export * from './moveAppointmentDialog';
export * from './qrCodeDialog';
export * from './patientDetail';
export * from './quickAddAppointment';
export { default as Dialog } from "./dialog";
export { default as DialogData } from "./config";
