version: "3" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
  medpro: #This is the name of our Nextjs application.
    command: >
        bash -c "npm run build && npm run start"
