apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: true
  tagPolicy:
    customTemplate:
      template: "{{.WORKSPACE}}-{{.SHA}}"
      components:
        - name: WORKSPACE
          envTemplate:
            template: "{{.WORKSPACE}}"
        - name: SHA
          gitCommit:
            variant: AbbrevCommitSha
            ignoreChanges: true
  artifacts:
    - image: ghcr.io/smartmedsa/med-pro
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [ "bash", "-c", "envsubst < .env.local.dist  > .env" ]

manifests:
  kustomize:
    paths:
      - ./kustomize/overlay/generic
  hooks:
    before:
      - host:
          command: [ "bash", "-c", " for FILE in ./kustomize/overlay/generic/*.tpl; do envsubst < $FILE > ${FILE/'.tpl'/} ; done" ]

    after:
      - host:
          command: [ "bash", "-c", "echo 'https://'${INGRESS_HOST}/ >> $GITHUB_OUTPUT" ]
      - host:
          command: [ "bash" , "-c", "for FILE in ./kustomize/overlay/generic/*.yaml; do [[ -e $FILE ]] && rm $FILE ; done"]
