import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {GetStaticProps} from "next";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import {useTranslation} from "next-i18next";

const Home: NextPage = () => {
    const { t, ready } = useTranslation('common');
    if (!ready) return (<>loading translations...</>);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <footer className={styles.footer}>
        <p>
          {t('powered_by') + ' '}
          <span className={styles.logo}>
            <Image src="/static/icons/Med-logo.svg" alt="Med Logo" width={40} height={30} />
          </span>
        </p>
      </footer>
    </div>
  )
}
export const getStaticProps: GetStaticProps = async ({ locale }) => ({
    props: {
        ...(await serverSideTranslations(locale as string, ['common']))
    }
})
export default Home
