import {useAppDispatch, useAppSelector} from "@app/redux/hooks";
import {setConfig} from "../setConfig/selectors";
import {useEffect} from "react";
import {setDirection} from "../setConfig/actions";
import {useRouter} from "next/router";
import createCache from "@emotion/cache";
import {prefixer} from "stylis";
import rtlPlugin from "stylis-plugin-rtl";
import {CacheProvider} from "@emotion/react";
import Head from "next/head";


type LayoutProps = {
    children: React.ReactNode,
};

export default function Layout({ children }: LayoutProps) {
    const router = useRouter();
    const dispatch = useAppDispatch();
    const config = useAppSelector(setConfig);
    // Create rtl cache
    const cacheRtl = createCache({
        key: config.direction === 'rtl' ? 'muirtl': 'css',
        stylisPlugins: config.direction === 'rtl' ? [prefixer, rtlPlugin] : []
    });
    cacheRtl.compat = true;

    useEffect(() => {
        const handleRouteChange = (url: string, { shallow }: any) => {
            let lang = 'fr';
            if(url.includes('/ar/') || url === '/ar'){
                lang = 'ar';
            }
            dispatch(setDirection(lang === 'ar' ? 'rtl': 'ltr'));
        }

        router.events.on('routeChangeStart', handleRouteChange);

        // If the component is unmounted, unsubscribe
        // from the event with the `off` method:
        return () => {
            router.events.off('routeChangeStart', handleRouteChange);
        }
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main dir={config.direction}>
                {config.direction === 'rtl' ?
                    <CacheProvider value={cacheRtl}>
                        {children}
                    </CacheProvider>
                    :
                    <>
                        {children}
                    </>
                }
            </main>
        </>
    )
}
