import {useAppDispatch} from "@app/redux/hooks";
import {useEffect} from "react";
import {setDirection} from "../setConfig/actions";
import {useRouter} from "next/router";
import createCache from "@emotion/cache";
import {prefixer} from "stylis";
import rtlPlugin from "stylis-plugin-rtl";
import {CacheProvider} from "@emotion/react";
import Head from "next/head";


type LayoutProps = {
    children: React.ReactNode,
};

export default function Layout({ children }: LayoutProps) {
    const router = useRouter();
    const dir = router.locale === 'ar' ? 'rtl': 'ltr';
    const dispatch = useAppDispatch();

    useEffect(() => {
        dispatch(setDirection(dir));
    }, [dir]);

    // Create rtl cache
    const cacheRtl = createCache({
        key: dir === 'rtl' ? 'muirtl': 'css',
        stylisPlugins: dir === 'rtl' ? [prefixer, rtlPlugin] : []
    });
    cacheRtl.compat = true;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main dir={dir}>
                {dir === 'rtl' ?
                    <CacheProvider value={cacheRtl}>
                        {children}
                    </CacheProvider>
                    :
                    <>
                        {children}
                    </>
                }
            </main>
        </>
    )
}
