/* This file was automatically generated by the typescript:generate command. */
interface PatientWithNextAndLatestAppointment {
    uuid: string;
    fiche_id: string;
    firstName: string;
    lastName: string;
    email: string;
    birthdate: string;
    account: AccountModel;
    gender: string;
    cin: string;
    profession: string;
    familyDoctor: string;
    insurances: PatientInsuranceModel[];
    contact: ContactModel[];
    address: AddressModel[];
    isParent: boolean;
    medicalEntityPatientBase: MedicalEntityPatientBaseModel[];
    nextAppointment: AppointmentModel;
    latestAppointment: AppointmentModel;
    patient: Patient;
    locale: string;
    nationality: CountryModel
}
