/* This file was automatically generated by the typescript:generate command. */
interface PrescriptionParentModel {
    uuid: string;
    name: string;
    prescriptionModels: PrescriptionModalModel[];
}
