/* This file was automatically generated by the typescript:generate command. */
interface PrescriptionModalModel {
  uuid: string;
  globalNote: string;
  name:string;
  prescriptionModalHasDrugs: PrescriptionModalHasDrugsModel[];
}