/* This file was automatically generated by the typescript:generate command. */
interface PrescriptionPatternModel {
    id: string;
    isDefault?: boolean;
    parent: number | string;
    droppable?: boolean;
    text: string;
}
