export * from "./personalInfoCard";
export * from "./backgroundCard";
export * from "./rdvCard";
export * from "./rdvMobileCard";
export * from "./patientDetailsDocumentCard";
export * from "./successCard";
export * from "./noDataCard";
export { default as DetailsCard } from "./detailsCard";
export { default as CollapseCard } from "./collapseCard";
export { default as ConsultationCard } from "./consultationCard";
export { default as QuestionCard } from "./questionCard";
export { default as PatientdetailsCard } from "./patientdetailsCard";
