name: Cleanup Artifacts

on:
  pull_request:
    branches:
      - 'develop'
    types: [closed]

jobs:
  delete:
    if: ((github.event.action == 'closed' || github.event.pull_request.merged == true))
    uses: ./.github/workflows/docker_delete.yml
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      tag: pr-${{ github.event.number }}
    secrets:
      token: ${{ secrets.SMARTMEDBOT_PAT }}
