name: Single Manual Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  CD:
    uses: SmartMedSA/github-workflows/.github/workflows/skaffold.yml@v1.1.0
    if: ${{ github.ref == 'refs/heads/main' && startsWith( inputs.environment , 'prod-' ) }}
    with:
      cmd: skaffold run
      environment: ${{ inputs.environment }}
      version: "2.0.4"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      ENV_VARS: |
        ${{ secrets.ENV_VARS }}
        INGRESS_TARGET=${{ secrets.INGRESS_TARGET }}
        INGRESS_HOST=${{ (secrets.INGRESS_HOST) }}
        NEXTAUTH_URL=https://${{ (secrets.INGRESS_HOST) }}
        SKAFFOLD_KUBE_CONTEXT=${{ secrets.SKAFFOLD_KUBE_CONTEXT }}
        SKAFFOLD_NAMESPACE=${{ secrets.SKAFFOLD_NAMESPACE }}
        SKAFFOLD_CACHE_ARTIFACTS=false
        WORKSPACE=${{ inputs.environment }}
